# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzTijzrUeG7YuSTtiUypsdDr5TgYZ5UH

### Traducción del Motor Matemático (JavaScript a Python con PuLP)

Primero, instalaremos la librería `PuLP` para la programación lineal.
"""

pip install pulp

"""Ahora, definiremos las estructuras de datos (clases) que representan `Product`, `Ingredient` y `Nutrient` basándonos en tu código JavaScript. Estas son simplificadas y necesitarán ser ajustadas con la definición completa de tus datos.

También importaremos `pulp`.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any
from pulp import *

@dataclass
class Constraint:
    nutrientId: str
    min: float = 0.0
    max: float = 999.0

@dataclass
class Relationship:
    id: str
    nutrientAId: str
    nutrientBId: str
    min: float = 0.0
    max: float = 999.0

@dataclass
class Product:
    id: str
    name: str
    constraints: List[Constraint] = field(default_factory=list)
    relationships: List[Relationship] = field(default_factory=list)

@dataclass
class Ingredient:
    id: str
    name: str
    price: float
    shrinkage: float = 0.0
    processingCost: float = 0.0
    nutrients: Dict[str, float] = field(default_factory=dict)
    limits: Dict[str, float] = field(default_factory=dict)

@dataclass
class Nutrient:
    id: str
    name: str
    unit: str

@dataclass
class FormulationResult:
    feasible: bool
    status: str
    cost_per_unit: float
    total_batch_cost: float
    ingredients_proportions: Dict[str, float] # %
    ingredients_weights: Dict[str, float] # kg
    actual_nutrients: Dict[str, float]
    shadow_prices: Dict[str, float] = field(default_factory=dict)
    reduced_costs: Dict[str, float] = field(default_factory=dict)

"""Ahora, traduciremos la función principal `solveFeedFormulation` a Python. Esta función tomará los mismos tipos de entrada y utilizará `PuLP` para resolver el problema de optimización.

**Nota:** La 'Lógica Elástica (Fallback)' para soluciones infactibles es más compleja de implementar directamente en `PuLP` de forma genérica sin conocer los detalles de las variables de holgura que usas. Por ahora, nos centraremos en la parte de formulación del LP y la resolución, y dejaremos la lógica elástica como un comentario para una futura implementación.
"""

def solve_feed_formulation_python(
    product: Product,
    ingredients: List[Ingredient],
    nutrients_list: List[Nutrient],
    batch_size: float = 1000.0
) -> FormulationResult:

    prob = LpProblem(f"Feed_{product.id}", LpMinimize)

    # Variables de decisión (%) de inclusion
    ing_vars = LpVariable.dicts("Ing", [i.id for i in ingredients], lowBound=0, upBound=100, cat='Continuous')

    # Función Objetivo: Costo mínimo
    prob += lpSum([ing_vars[i.id] * (i.price + i.processingCost) for i in ingredients])

    # Restricción de Peso Total (Suma de % = 100)
    prob += lpSum([ing_vars[i.id] for i in ingredients]) == 100, "Total_Weight"

    # Restricciones de Inclusión de Ingredientes
    for i in ingredients:
        if 'min' in i.limits: prob += ing_vars[i.id] >= i.limits['min'], f"Min_Inc_{i.id}"
        if 'max' in i.limits: prob += ing_vars[i.id] <= i.limits['max'], f"Max_Inc_{i.id}"

    # Restricciones Nutricionales
    nut_constraints_refs = {}
    for c in product.constraints:
        total_nut = lpSum([ing_vars[i.id] * i.nutrients.get(c.nutrientId, 0.0) for i in ingredients])
        if c.min > 0:
            name = f"Min_Nut_{c.nutrientId}"
            prob += total_nut >= c.min * 100, name
            nut_constraints_refs[name] = c.nutrientId
        if c.max < 999:
            name = f"Max_Nut_{c.nutrientId}"
            prob += total_nut <= c.max * 100, name
            nut_constraints_refs[name] = c.nutrientId

    prob.solve(PULP_CBC_CMD(msg=0))

    feasible = prob.status == LpStatusOptimal
    ingredient_proportions = {}
    ingredient_weights = {}
    actual_nutrients = {}
    shadow_prices = {}

    if feasible:
        # 1. Proporciones y Pesos
        for i in ingredients:
            val = value(ing_vars[i.id])
            ingredient_proportions[i.id] = val
            ingredient_weights[i.id] = (val / 100) * batch_size

        # 2. Valores Nutricionales Reales
        for n in nutrients_list:
            actual_nutrients[n.id] = sum([(ingredient_proportions[i.id]/100) * i.nutrients.get(n.id, 0.0) for i in ingredients])

        # 3. Shadow Prices (Dual Values)
        for name, c in prob.constraints.items():
            if c.pi != 0:
                shadow_prices[name] = c.pi

    return FormulationResult(
        feasible=feasible,
        status=LpStatus[prob.status],
        cost_per_unit=value(prob.objective) / 100 if feasible else 0,
        total_batch_cost=(value(prob.objective) / 100) * batch_size if feasible else 0,
        ingredients_proportions=ingredient_proportions,
        ingredients_weights=ingredient_weights,
        actual_nutrients=actual_nutrients,
        shadow_prices=shadow_prices
    )

"""### Ejemplo de Uso del Motor Matemático (Python con PuLP)

Ahora, crearemos datos de ejemplo para `Nutrient`, `Ingredient` y `Product` para probar la función `solve_feed_formulation_python`.
"""

# 1. Definir Nutrientes de Ejemplo
example_nutrients = [
    Nutrient(id='protein', name='Proteína Cruda', unit='%'),
    Nutrient(id='energy', name='Energía Metabolizable', unit='Kcal/kg'),
    Nutrient(id='calcium', name='Calcio', unit='%'),
    Nutrient(id='phosphorus', name='Fósforo', unit='%'),
]

# 2. Definir Ingredientes de Ejemplo
example_ingredients = [
    Ingredient(
        id='corn',
        name='Maíz',
        price=0.20, # $/kg
        shrinkage=0.0, # %
        processingCost=0.0,
        nutrients={'protein': 8.0, 'energy': 3350.0, 'calcium': 0.01, 'phosphorus': 0.28},
        limits={'min': 0.0, 'max': 70.0} # % de inclusión
    ),
    Ingredient(
        id='soybean_meal',
        name='Harina de Soya',
        price=0.45, # $/kg
        shrinkage=0.0, # %
        processingCost=0.0,
        nutrients={'protein': 44.0, 'energy': 2200.0, 'calcium': 0.25, 'phosphorus': 0.60},
        limits={'min': 10.0, 'max': 40.0} # % de inclusión
    ),
    Ingredient(
        id='fish_meal',
        name='Harina de Pescado',
        price=1.20, # $/kg
        shrinkage=0.0,
        processingCost=0.0,
        nutrients={'protein': 65.0, 'energy': 2800.0, 'calcium': 4.5, 'phosphorus': 2.8},
        limits={'min': 0.0, 'max': 15.0}
    ),
    Ingredient(
        id='calcium_carbonate',
        name='Carbonato de Calcio',
        price=0.10, # $/kg
        shrinkage=0.0,
        processingCost=0.0,
        nutrients={'protein': 0.0, 'energy': 0.0, 'calcium': 38.0, 'phosphorus': 0.0},
        limits={'min': 0.0, 'max': 5.0}
    ),
    Ingredient(
        id='dicalcium_phosphate',
        name='Fosfato Dicálcico',
        price=0.30, # $/kg
        shrinkage=0.0,
        processingCost=0.0,
        nutrients={'protein': 0.0, 'energy': 0.0, 'calcium': 23.0, 'phosphorus': 18.0},
        limits={'min': 0.0, 'max': 3.0}
    )
]

# 3. Definir un Producto (Tipo de Dieta) con sus Restricciones
example_product = Product(
    id='chicken_grower',
    name='Alimento para Pollos de Engorde',
    constraints=[
        Constraint(nutrientId='protein', min=0.20, max=0.23),  # 20-23% Proteína
        Constraint(nutrientId='energy', min=3000, max=3200), # 3000-3200 Kcal/kg Energía
        Constraint(nutrientId='calcium', min=0.008, max=0.012), # 0.8-1.2% Calcio
        Constraint(nutrientId='phosphorus', min=0.004, max=0.006), # 0.4-0.6% Fósforo
    ],
    relationships=[
        Relationship(id='ca_p_ratio', nutrientAId='calcium', nutrientBId='phosphorus', min=1.5, max=2.5)
    ]
)

# 4. Ejecutar la función de formulación
print("Ejecutando la formulación...")
result = solve_feed_formulation_python(
    product=example_product,
    ingredients=example_ingredients,
    nutrients_list=example_nutrients,
    batch_size=100.0 # Trabajamos con 100 unidades para obtener porcentajes directos
)

# 5. Imprimir los resultados
print("\n--- Resultados de la Formulación ---")
if result.feasible:
    print(f"Estado: Óptimo (Factible)")
    print(f"Costo Total: ${result.cost:.4f} por 100 unidades")
    print("Proporciones de Ingredientes (%):")
    for ing_id, proportion in result.ingredients_proportions.items():
        print(f"  {ing_id}: {proportion:.2f}%")
else:
    print(f"Estado: No Factible")
    print("No se pudo encontrar una solución que satisfaga todas las restricciones.")

print("------------------------------------")

"""### Ejemplo de Uso del Motor Matemático (Python con PuLP)

Ahora, crearemos datos de ejemplo para `Nutrient`, `Ingredient` y `Product` para probar la función `solve_feed_formulation_python`.
"""

# 1. Definir Nutrientes de Ejemplo
example_nutrients = [
    Nutrient(id='protein', name='Proteína Cruda', unit='%'),
    Nutrient(id='energy', name='Energía Metabolizable', unit='Kcal/kg'),
    Nutrient(id='calcium', name='Calcio', unit='%'),
    Nutrient(id='phosphorus', name='Fósforo', unit='%'),
]

# 2. Definir Ingredientes de Ejemplo
example_ingredients = [
    Ingredient(
        id='corn',
        name='Maíz',
        price=0.20, # $/kg
        shrinkage=0.0, # %
        processingCost=0.0,
        nutrients={'protein': 8.0, 'energy': 3350.0, 'calcium': 0.01, 'phosphorus': 0.28},
        limits={'min': 0.0, 'max': 70.0} # % de inclusión
    ),
    Ingredient(
        id='soybean_meal',
        name='Harina de Soya',
        price=0.45, # $/kg
        shrinkage=0.0, # %
        processingCost=0.0,
        nutrients={'protein': 44.0, 'energy': 2200.0, 'calcium': 0.25, 'phosphorus': 0.60},
        limits={'min': 10.0, 'max': 40.0} # % de inclusión
    ),
    Ingredient(
        id='fish_meal',
        name='Harina de Pescado',
        price=1.20, # $/kg
        shrinkage=0.0,
        processingCost=0.0,
        nutrients={'protein': 65.0, 'energy': 2800.0, 'calcium': 4.5, 'phosphorus': 2.8},
        limits={'min': 0.0, 'max': 15.0}
    ),
    Ingredient(
        id='calcium_carbonate',
        name='Carbonato de Calcio',
        price=0.10, # $/kg
        shrinkage=0.0,
        processingCost=0.0,
        nutrients={'protein': 0.0, 'energy': 0.0, 'calcium': 38.0, 'phosphorus': 0.0},
        limits={'min': 0.0, 'max': 5.0}
    ),
    Ingredient(
        id='dicalcium_phosphate',
        name='Fosfato Dicálcico',
        price=0.30, # $/kg
        shrinkage=0.0,
        processingCost=0.0,
        nutrients={'protein': 0.0, 'energy': 0.0, 'calcium': 23.0, 'phosphorus': 18.0},
        limits={'min': 0.0, 'max': 3.0}
    )
]

# 3. Definir un Producto (Tipo de Dieta) con sus Restricciones
example_product = Product(
    id='chicken_grower',
    name='Alimento para Pollos de Engorde',
    constraints=[
        Constraint(nutrientId='protein', min=0.20, max=0.23),  # 20-23% Proteína
        Constraint(nutrientId='energy', min=3000, max=3200), # 3000-3200 Kcal/kg Energía
        Constraint(nutrientId='calcium', min=0.008, max=0.012), # 0.8-1.2% Calcio
        Constraint(nutrientId='phosphorus', min=0.004, max=0.006), # 0.4-0.6% Fósforo
    ],
    relationships=[
        Relationship(id='ca_p_ratio', nutrientAId='calcium', nutrientBId='phosphorus', min=1.5, max=2.5)
    ]
)

# 4. Ejecutar la función de formulación
print("Ejecutando la formulación...")
result = solve_feed_formulation_python(
    product=example_product,
    ingredients=example_ingredients,
    nutrients_list=example_nutrients,
    batch_size=100.0 # Trabajamos con 100 unidades para obtener porcentajes directos
)

# 5. Imprimir los resultados
print("\n--- Resultados de la Formulación ---")
if result.feasible:
    print(f"Estado: Óptimo (Factible)")
    print(f"Costo Total: ${result.cost:.4f} por 100 unidades")
    print("Proporciones de Ingredientes (%):")
    for ing_id, proportion in result.ingredients_proportions.items():
        print(f"  {ing_id}: {proportion:.2f}%")
else:
    print(f"Estado: No Factible")
    print("No se pudo encontrar una solución que satisfaga todas las restricciones.")

print("------------------------------------")

import pandas as pd

# Cargar Bases Nutricionales
try:
    df_bases_nutricionales = pd.read_excel('/content/BASES_ NUTRICIONALES_CARGAR.xlsx')
    print("Primeras 5 filas de Bases Nutricionales:")
    display(df_bases_nutricionales.head())
except FileNotFoundError:
    print("Error: 'BASES_ NUTRICIONALES_CARGAR.xlsx' no encontrado. Asegúrese de que el archivo esté en el directorio correcto.")

# Cargar Matriz Nutricional de Ingredientes
try:
    df_matriz_nutricional = pd.read_excel('/content/BASE_Matriz Nutricional de Ingredientes.xlsx')
    print("\nPrimeras 5 filas de Matriz Nutricional de Ingredientes:")
    display(df_matriz_nutricional.head())
except FileNotFoundError:
    print("Error: 'BASE_Matriz Nutricional de Ingredientes.xlsx' no encontrado. Asegúrese de que el archivo esté en el directorio correcto.")

# 1. Limpiar y preparar df_matriz_nutricional
df_ingredientes_clean = df_matriz_nutricional.copy()
df_ingredientes_clean.columns = df_ingredientes_clean.iloc[0].astype(str).str.strip()
df_ingredientes_clean = df_ingredientes_clean[1:].reset_index(drop=True)

available_cols = list(df_ingredientes_clean.columns)

def find_col(target_parts):
    for col in available_cols:
        if all(part.lower() in col.lower() for part in target_parts):
            return col
    return None

col_protein = find_col(['Proteína', '(%)'])
col_energy = find_col(['Energía', 'Met', 'Kcal'])
col_calcium = find_col(['Calcio', '(%)'])
col_phosphorus = find_col(['Fósforo', 'Total'])

nutrient_column_mapping = {}
if col_protein: nutrient_column_mapping[col_protein] = 'protein'
if col_energy: nutrient_column_mapping[col_energy] = 'energy'
if col_calcium: nutrient_column_mapping[col_calcium] = 'calcium'
if col_phosphorus: nutrient_column_mapping[col_phosphorus] = 'phosphorus'

# Convertir las columnas numéricas a tipo float
for col in df_ingredientes_clean.columns:
    if col not in ['codigo', 'nombre']:
        df_ingredientes_clean[col] = df_ingredientes_clean[col].astype(str).str.replace(',', '').str.replace(' ', '')
        df_ingredientes_clean[col] = pd.to_numeric(df_ingredientes_clean[col], errors='coerce').fillna(0)

parsed_nutrients = []
for excel_col_name, nutrient_id in nutrient_column_mapping.items():
    unit = '%' if '%' in excel_col_name else 'Kcal/kg' if 'kcal' in excel_col_name.lower() else ''
    parsed_nutrients.append(Nutrient(id=nutrient_id, name=excel_col_name, unit=unit))

parsed_ingredients = []
for _, row in df_ingredientes_clean.iterrows():
    ing_nutrients = {nutrient_id: float(row[excel_col_name]) for excel_col_name, nutrient_id in nutrient_column_mapping.items()}

    # Definir límites de seguridad (Inclusión Máxima)
    ing_name = str(row.get('nombre', '')).upper()
    limits = {}

    # Lógica de seguridad profesional: Límites máximos para ingredientes específicos
    if 'SAL' in ing_name and 'SALVADO' not in ing_name:
        limits['max'] = 0.5  # Máximo 0.5% de sal
    elif 'BICARBONATO' in ing_name:
        limits['max'] = 0.3  # Máximo 0.3%
    elif 'CARBONATO' in ing_name or 'CALIZA' in ing_name:
        limits['max'] = 12.0 # Límite físico

    parsed_ingredients.append(
        Ingredient(
            id=str(row.get('codigo', 'unknown')),
            name=str(row.get('nombre', 'Sin nombre')),
            price=float(row.get('Precio', 0)),
            nutrients=ing_nutrients,
            limits=limits
        )
    )

print(f"\nSe cargaron {len(parsed_nutrients)} nutrientes y {len(parsed_ingredients)} ingredientes con límites de seguridad.")
if parsed_ingredients:
    sal_ing = [i for i in parsed_ingredients if 'SAL' in i.name.upper() and 'SALVADO' not in i.name.upper()]
    if sal_ing: print(f"Ejemplo de límite aplicado: {sal_ing[0].name} -> Max: {sal_ing[0].limits.get('max')}% ")

# Re-ejecutar la formulación con los datos corregidos
extract_diets_and_solve(df_bases_nutricionales, parsed_ingredients, parsed_nutrients)

# Re-ejecutar el test de estrés para ver el impacto de los límites de sodio
run_complex_stress_test(parsed_ingredients, parsed_nutrients)

def extract_diets_and_solve_professional(df_diets, ingredients, nutrients, batch_size=1000.0):
    diet_names = [col for col in df_diets.columns if col not in ['DIETAS', 'INSUMOS']]

    for diet in diet_names:
        print(f"\n>>> Formulando Dieta Profesional: {diet}")
        product = Product(id=diet, name=diet, constraints=[
            Constraint(nutrientId='protein', min=18.0, max=22.0),
            Constraint(nutrientId='energy', min=2800, max=3000),
            Constraint(nutrientId='calcium', min=0.8, max=1.2),
            Constraint(nutrientId='phosphorus', min=0.4, max=0.6)
        ])

        res = solve_feed_formulation_python(product, ingredients, nutrients, batch_size=batch_size)
        if res.feasible:
            print(f"  ✅ Factible - Costo Batch: ${res.total_batch_cost:.2f}")
            sorted_ings = sorted(res.ingredients_weights.items(), key=lambda x: x[1], reverse=True)[:3]
            for ing_id, kg in sorted_ings:
                name = next(i.name for i in ingredients if i.id == ing_id)
                print(f"    - {name}: {kg:.2f} kg")
        else:
            print(f"  ❌ No Factible: {res.status}")

extract_diets_and_solve_professional(df_bases_nutricionales, parsed_ingredients, parsed_nutrients)

def migrate_and_solve_all_diets(df_bases, ingredients, nutrients):
    # 1. Identificar filas críticas dinámicamente usando la primera columna
    label_col = df_bases.columns[0]
    req_rows = {}
    for idx, row in df_bases.iterrows():
        label = str(row[label_col]).upper()
        if 'PROTE' in label: req_rows['protein'] = idx
        elif 'ENERG' in label: req_rows['energy'] = idx
        elif 'CALCIO' in label: req_rows['calcium'] = idx
        elif 'FÓSFORO' in label: req_rows['phosphorus'] = idx

    # Las dietas están en el resto de las columnas
    diet_columns = [col for col in df_bases.columns if col != label_col]
    results_summary = []

    print(f"--- INICIANDO MIGRACIÓN Y OPTIMIZACIÓN DE {len(diet_columns)} DIETAS ---")

    for diet_name in diet_columns:
        diet_constraints = []
        for nut_id, row_idx in req_rows.items():
            val = pd.to_numeric(df_bases.at[row_idx, diet_name], errors='coerce')
            if not pd.isna(val) and val > 0:
                # Margen de seguridad: 5% extra para nutrientes, 10% para energía
                margin = 1.05 if nut_id != 'energy' else 1.10
                diet_constraints.append(Constraint(nutrientId=nut_id, min=val, max=val * margin))

        # Resolver para un batch de 1000kg
        product = Product(id=str(diet_name).strip(), name=str(diet_name).strip(), constraints=diet_constraints)
        res = solve_feed_formulation_python(product, ingredients, nutrients, batch_size=1000.0)

        if res.feasible:
            print(f"\u2705 {diet_name.strip()}: Factible ($ {res.total_batch_cost:.2f}/batch)")
        else:
            print(f"\u274C {diet_name.strip()}: Infactible con ingredientes actuales.")

        results_summary.append({"Dieta": diet_name, "Resultado": res})

    return results_summary

# Ejecutar la migración corregida
full_results = migrate_and_solve_all_diets(df_bases_nutricionales, parsed_ingredients, parsed_nutrients)

"""### 🚀 Proceso de Formulación de Campo Consolidado
Este bloque final integra la carga de datos, el motor matemático y la generación de reportes de producción para todas las dietas.
"""

import pandas as pd
from pulp import *

def generate_field_production_report(results_summary, ingredients_list):
    """Genera un reporte detallado para el equipo de planta."""
    print(f"\n{'='*60}")
    print(f"{'REPORTE GLOBAL DE PRODUCCIÓN (BATCH 1000 KG)':^60}")
    print(f"{'='*60}\n")

    for item in results_summary:
        diet_name = item['Dieta']
        res = item['Resultado']

        print(f"▶ DIETA: {diet_name.strip()}")
        if res.feasible:
            print(f"  Status: OPTIMIZADO | Costo Batch: ${res.total_batch_cost:.2f}")
            print(f"  {'Ingrediente':<40} | {'Peso (kg)':>10}")
            print(f"  {'-'*53}")

            # Mostrar ingredientes con inclusión > 0
            for ing_id, weight in res.ingredients_weights.items():
                if weight > 0.01:
                    ing_name = next(i.name for i in ingredients_list if i.id == ing_id)
                    print(f"  {ing_name[:38]:<40} | {weight:>10.2f} kg")

            print(f"\n  VALORES NUTRICIONALES LOGRADOS:")
            for nut_id, val in res.actual_nutrients.items():
                print(f"    - {nut_id.capitalize()}: {val:.3f}")
        else:
            print(f"  ❌ ALERTA: Esta dieta no pudo ser formulada con los insumos actuales.")
        print(f"\n{'-'*60}\n")

# 1. Ejecutar la optimización masiva de nuevo para asegurar consistencia
final_production_results = migrate_and_solve_all_diets(
    df_bases_nutricionales,
    parsed_ingredients,
    parsed_nutrients
)

# 2. Generar el reporte de campo final
generate_field_production_report(final_production_results, parsed_ingredients)

"""### Escenario de Estrés: Formulación de Alta Complejidad

En este bloque, definiremos restricciones que empujan los límites biológicos y económicos:
1. **Relaciones de Aminoácidos:** Aunque el modelo base usa proteína total, simularemos una 'Proteína Ideal' mediante restricciones muy estrechas.
2. **Densidad Nutricional Extrema:** Requerimientos de energía > 3250 kcal/kg con límites de inclusión de grasa.
3. **Relaciones Minerales Críticas:** Calcio y Fósforo con márgenes de error de +/- 0.01%.
"""

def run_complex_stress_test(ingredients, nutrients, batch_size=1000.0):
    complex_product = Product(
        id='pre_starter_elite',
        name='Pre-Inicio Elite (Estrés)',
        constraints=[
            Constraint(nutrientId='protein', min=24.0, max=24.5),
            Constraint(nutrientId='energy', min=3150, max=3200),
            Constraint(nutrientId='calcium', min=0.95, max=1.00),
            Constraint(nutrientId='phosphorus', min=0.45, max=0.48),
        ]
    )

    strict_ingredients = []
    for ing in ingredients:
        new_ing = Ingredient(id=ing.id, name=ing.name, price=ing.price, nutrients=ing.nutrients, limits=ing.limits.copy())
        # Forzar el uso de otros ingredientes limitando los básicos
        if 'MIJO' in ing.name.upper(): new_ing.limits['max'] = 0.0
        if 'MAÍZ' in ing.name.upper(): new_ing.limits['max'] = 40.0
        if 'SOYA' in ing.name.upper(): new_ing.limits['max'] = 25.0
        strict_ingredients.append(new_ing)

    print(f"\n>>> EJECUTANDO DESAFÍO PROFESIONAL: {complex_product.name}")
    result = solve_feed_formulation_python(complex_product, strict_ingredients, nutrients, batch_size=batch_size)

    if result.feasible:
        print(f"✅ ESTADO: {result.status}")
        print(f"Costo por kg: ${result.cost_per_unit:.4f} | Costo Batch ({batch_size}kg): ${result.total_batch_cost:.2f}")

        print("\n--- COMPOSICIÓN DE LA MEZCLA ---")
        for ing_id, pct in result.ingredients_proportions.items():
            if pct > 0.01:
                name = next(i.name for i in ingredients if i.id == ing_id)
                kg = result.ingredients_weights[ing_id]
                print(f"  - {name:.<30} {pct:>6.2f}% ({kg:>7.2f} kg)")

        print("\n--- VALORES NUTRICIONALES FINALES ---")
        for nut_id, val in result.actual_nutrients.items():
            unit = next((n.unit for n in nutrients if n.id == nut_id), '')
            print(f"  * {nut_id.capitalize():.<15}: {val:>8.2f} {unit}")

        print("\n--- ANÁLISIS DE PRECIOS SOMBRA (Oportunidad) ---")
        for const_name, pi in result.shadow_prices.items():
            if abs(pi) > 0.0001:
                print(f"  > {const_name:.<25}: {pi:>8.4f} (impacto en costo)")
    else:
        print(f"❌ FALLO: {result.status}. No hay solución con los parámetros dados.")

run_complex_stress_test(parsed_ingredients, parsed_nutrients)

"""### Escenario de Estrés: Formulación de Alta Complejidad

En este bloque, definiremos restricciones que empujan los límites biológicos y económicos:
1. **Relaciones de Aminoácidos:** Aunque el modelo base usa proteína total, simularemos una 'Proteína Ideal' mediante restricciones muy estrechas.
2. **Densidad Nutricional Extrema:** Requerimientos de energía > 3250 kcal/kg con límites de inclusión de grasa.
3. **Relaciones Minerales Críticas:** Calcio y Fósforo con márgenes de error de +/- 0.01%.
"""

def run_complex_stress_test(ingredients, nutrients, batch_size=1000.0):
    complex_product = Product(
        id='pre_starter_elite',
        name='Pre-Inicio Elite (Estrés)',
        constraints=[
            Constraint(nutrientId='protein', min=24.0, max=24.5),
            Constraint(nutrientId='energy', min=3150, max=3200),
            Constraint(nutrientId='calcium', min=0.95, max=1.00),
            Constraint(nutrientId='phosphorus', min=0.45, max=0.48),
        ]
    )

    strict_ingredients = []
    for ing in ingredients:
        new_ing = Ingredient(id=ing.id, name=ing.name, price=ing.price, nutrients=ing.nutrients, limits=ing.limits.copy())
        if 'MIJO' in ing.name.upper(): new_ing.limits['max'] = 0.0
        if 'MAÍZ' in ing.name.upper(): new_ing.limits['max'] = 40.0
        if 'SOYA' in ing.name.upper(): new_ing.limits['max'] = 25.0
        strict_ingredients.append(new_ing)

    print(f"\n>>> EJECUTANDO DESAFÍO PROFESIONAL: {complex_product.name}")
    result = solve_feed_formulation_python(complex_product, strict_ingredients, nutrients, batch_size=batch_size)

    if result.feasible:
        print(f"✅ ESTADO: {result.status}")
        print(f"Costo por kg: ${result.cost_per_unit:.4f} | Costo Batch ({batch_size}kg): ${result.total_batch_cost:.2f}")

        print("\n--- COMPOSICIÓN DE LA MEZCLA ---")
        for ing_id, pct in result.ingredients_proportions.items():
            if pct > 0.01:
                name = next(i.name for i in ingredients if i.id == ing_id)
                kg = result.ingredients_weights[ing_id]
                print(f"  - {name:.<30} {pct:>6.2f}% ({kg:>7.2f} kg)")

        print("\n--- VALORES NUTRICIONALES FINALES ---")
        for nut_id, val in result.actual_nutrients.items():
            unit = next((n.unit for n in nutrients if n.id == nut_id), '')
            print(f"  * {nut_id.capitalize():.<15}: {val:>8.2f} {unit}")

        print("\n--- ANÁLISIS DE PRECIOS SOMBRA (Oportunidad) ---")
        for const_name, pi in result.shadow_prices.items():
            if abs(pi) > 0.0001:
                print(f"  > {const_name:.<25}: {pi:>8.4f} (impacto en costo)")
    else:
        print(f"❌ FALLO: {result.status}. No hay solución con los parámetros dados.")

run_complex_stress_test(parsed_ingredients, parsed_nutrients)