export const INITIAL_INGREDIENTS: Ingredient[] = [
  { id: 'i1', code: 100010, name: 'Maíz', category: 'MACRO', subcategory: 'CEREALES', family: 'MAIZ', price: 0, stock: 0, nutrients: {} },
  { id: 'i2', code: 100020, name: 'Maíz, baja CP', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i3', code: 100030, name: 'Maíz Chile', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i4', code: 100040, name: 'Maíz, alto aceite', category: 'MACRO', subcategory: 'CEREALES', family: 'MAIZ', price: 0, stock: 0, nutrients: {} },
  { id: 'i5', code: 100050, name: 'Sorgo, tanino<0,5', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i6', code: 100060, name: 'Sorgo, tanino>0,5', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i7', code: 100070, name: 'Mijo, grano', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i8', code: 100080, name: 'Triticale', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i9', code: 100090, name: 'Cebada', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i10', code: 100100, name: 'Avena', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i11', code: 100110, name: 'Trigo, grano 13', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i12', code: 100120, name: 'Trigo, residuo', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i13', code: 100130, name: 'Arroz, quebrado', category: 'MACRO', subcategory: 'CEREALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i14', code: 200010, name: 'Soja, inf. ext. 36', category: 'MACRO', subcategory: 'OLEAGINOSAS', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i15', code: 200020, name: 'Soja, micronizada', category: 'MACRO', subcategory: 'OLEAGINOSAS', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i16', code: 300010, name: 'Soja, pasta 43', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i17', code: 300020, name: 'Soja, pasta 44', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i18', code: 300030, name: 'Soja, pasta 45', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i19', code: 300040, name: 'Soja, pasta 46', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i20', code: 300050, name: 'Soja, pasta 47', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i21', code: 300060, name: 'Soja, pasta 48', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i22', code: 300070, name: 'Soja, cascara', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i23', code: 300080, name: 'Soja, concentrado proteico 90', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i24', code: 300090, name: 'Aceite de Soja', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'SOJA', price: 0, stock: 0, nutrients: {} },
  { id: 'i25', code: 300100, name: 'Arroz, harina integral', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i26', code: 300110, name: 'Arroz, harina desgrasada', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i27', code: 300120, name: 'Trigo, afrecho 15', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'TRIGO', price: 0, stock: 0, nutrients: {} },
  { id: 'i28', code: 300130, name: 'Trigo, afrecho 19', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'TRIGO', price: 0, stock: 0, nutrients: {} },
  { id: 'i29', code: 300140, name: 'Maíz, gluten 60', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'MAIZ', price: 0, stock: 0, nutrients: {} },
  { id: 'i30', code: 300150, name: 'Maíz, gluten 22', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'MAIZ', price: 0, stock: 0, nutrients: {} },
  { id: 'i31', code: 300160, name: 'Girasol, harina 30', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i32', code: 300170, name: 'Girasol, harina 35', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i33', code: 300180, name: 'Girasol, harina 40', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i34', code: 300190, name: 'Canola, harina', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i35', code: 300200, name: 'Coco, aceite', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i36', code: 300210, name: 'Aserrin', category: 'MACRO', subcategory: 'SUBPROD.VEGETAL', family: 'TRIGO', price: 0, stock: 0, nutrients: {} },
  { id: 'i37', code: 400010, name: 'Carne, harina 35', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'CARNE, HARINA', price: 0, stock: 0, nutrients: {} },
  { id: 'i38', code: 400020, name: 'Carne, harina 40', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'CARNE, HARINA', price: 0, stock: 0, nutrients: {} },
  { id: 'i39', code: 400030, name: 'Carne, harina 42', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i40', code: 400040, name: 'Carne, harina 45', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'CARNE, HARINA', price: 0, stock: 0, nutrients: {} },
  { id: 'i41', code: 400050, name: 'Carne, harina 50', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'CARNE, HARINA', price: 0, stock: 0, nutrients: {} },
  { id: 'i42', code: 400060, name: 'Carne, harina 50 (Dig.)', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i43', code: 400070, name: 'Carne, harina 55', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'CARNE, HARINA', price: 0, stock: 0, nutrients: {} },
  { id: 'i44', code: 400080, name: 'Visceras, Harina 52/12', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'VISCERAS, HARINA 52/12', price: 0, stock: 0, nutrients: {} },
  { id: 'i45', code: 400090, name: 'Pescado, harina', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i46', code: 400100, name: 'Sangre, harina 82', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i47', code: 400110, name: 'Sangre, plasma (AP920)', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'PLUMAS, HARINA', price: 0, stock: 0, nutrients: {} },
  { id: 'i48', code: 400120, name: 'Sangre, hemoglobina (AP301)', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i49', code: 400130, name: 'Pescado, harina 55', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i50', code: 400140, name: 'Pescado, harina 60', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i51', code: 400150, name: 'Pescado, harina 65', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i52', code: 400160, name: 'Casca, bovina', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i53', code: 400170, name: 'Grasa, aves', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i54', code: 400180, name: 'Lactosa', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'LÁCTEOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i55', code: 400190, name: 'Leche, polvo integral', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'LÁCTEOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i56', code: 400200, name: 'Leche, polvo descremada', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'LÁCTEOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i57', code: 400210, name: 'Suero, de leche dulce', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'LÁCTEOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i58', code: 400220, name: 'Suero de leche acido', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'LÁCTEOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i59', code: 400230, name: 'Sustituto, de leche K50 (Sloten)', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'LÁCTEOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i60', code: 400240, name: 'Sustituto, de leche K71 (Sloten)', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', family: 'LÁCTEOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i61', code: 400250, name: 'Levadura, de caña seca 35', category: 'MACRO', subcategory: 'SUBPROD.ANIMAL', price: 0, stock: 0, nutrients: {} },
  { id: 'i62', code: 500010, name: 'L-Lisina HCL 99', category: 'MICRO', subcategory: 'AMINOÁCIDOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i63', code: 500020, name: 'L-Treonina 98,5', category: 'MICRO', subcategory: 'AMINOÁCIDOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i64', code: 500030, name: 'DL-Metionina 99', category: 'MICRO', subcategory: 'AMINOÁCIDOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i65', code: 500040, name: 'L-Triptofano 98,5', category: 'MICRO', subcategory: 'AMINOÁCIDOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i66', code: 500050, name: 'L-Isoleucina 99%', category: 'MICRO', subcategory: 'AMINOÁCIDOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i67', code: 500060, name: 'L-Valina 99%', category: 'MICRO', subcategory: 'AMINOÁCIDOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i68', code: 600010, name: 'Sal comun', category: 'MICRO', subcategory: 'MINERALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i69', code: 600020, name: 'Calcareo', category: 'MICRO', subcategory: 'MINERALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i70', code: 600030, name: 'Huesos, harina calcinada', category: 'MICRO', subcategory: 'MINERALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i71', code: 600040, name: 'Fosfato Bicalcico 18', category: 'MICRO', subcategory: 'MINERALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i72', code: 600050, name: 'Óxido de Zinc', category: 'MICRO', subcategory: 'MINERALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i73', code: 600060, name: 'Sulfato de Cobre', category: 'MICRO', subcategory: 'MINERALES', price: 0, stock: 0, nutrients: {} },
  { id: 'i74', code: 700010, name: 'Cloruro de Colina 60 %', category: 'MICRO', subcategory: 'VITAMINAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i75', code: 700020, name: 'Antioxidante', category: 'MICRO', subcategory: 'VITAMINAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i76', code: 700030, name: 'BHT', category: 'MICRO', subcategory: 'VITAMINAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i77', code: 700040, name: 'BHA', category: 'MICRO', subcategory: 'VITAMINAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i78', code: 800010, name: 'Aroma', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i79', code: 800020, name: 'Palatabilizante', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i80', code: 800030, name: 'Enzima', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i81', code: 800040, name: 'Acidificante', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i82', code: 800050, name: 'Promotor', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i83', code: 800060, name: 'Colistina 8', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i84', code: 800070, name: 'Tilosina 98', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i85', code: 800080, name: 'Carbadox', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i86', code: 800090, name: 'Vermifugo', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i87', code: 800100, name: 'Caulim', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i88', code: 800110, name: 'Otros', category: 'MICRO', subcategory: 'ADITIVOS', price: 0, stock: 0, nutrients: {} },
  { id: 'i89', code: 900010, name: 'Premix Vitamínico', category: 'MICRO', subcategory: 'BLENDS', price: 0, stock: 0, nutrients: {} },
  { id: 'i90', code: 900020, name: 'Premix Micromineral', category: 'MICRO', subcategory: 'BLENDS', price: 0, stock: 0, nutrients: {} },
  { id: 'i91', code: 900030, name: 'Núcleo Crecimiento/01', category: 'MICRO', subcategory: 'BLENDS', price: 0, stock: 0, nutrients: {} },
  { id: 'i92', code: 900040, name: 'Núcleo Crecimiento/02', category: 'MICRO', subcategory: 'BLENDS', price: 0, stock: 0, nutrients: {} },
  { id: 'i93', code: 900050, name: 'Núcleo Crecimiento/03', category: 'MICRO', subcategory: 'BLENDS', price: 0, stock: 0, nutrients: {} },
  { id: 'i94', code: 1000010, name: 'Fitasa A', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i95', code: 1000020, name: 'Fitasa B', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i96', code: 1000030, name: 'Fitasa C', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i97', code: 1000040, name: 'Fitasa D', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i98', code: 1000050, name: 'Xilanasa A', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i99', code: 1000060, name: 'Xilanasa B', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i100', code: 1000070, name: 'Xilanasa C', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i101', code: 1000080, name: 'Xilanasa D', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i102', code: 1000090, name: 'Carbohidrasa A', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i103', code: 1000100, name: 'Carbohidrasa B', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i104', code: 1000110, name: 'Carbohidrasa C', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
  { id: 'i105', code: 1000120, name: 'Carbohidrasa D', category: 'MICRO', subcategory: 'ENZIMAS', price: 0, stock: 0, nutrients: {} },
];
